"""Tests for crucible.runner (artifact writer + audit engine + workflow runner)."""

import tempfile

from crucible.runner import ArtifactWriter, AuditEngine, WorkflowRunner


def test_artifact_writer_creates_nested_dirs(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("a/b/c/hello.py", "print('hi')\n")
    assert p.exists()
    assert "print('hi')" in p.read_text()
    assert len(writer.list_written()) == 1


def test_artifact_writer_adds_header(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("hello.md", "# Hi\n")
    text = p.read_text()
    assert text.startswith("# Generated by crucible")
    assert "# Hi" in text


def test_artifact_writer_writes_module(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write_module(
        "mymodule.py",
        "A demo module.",
        "X = 1\n",
    )
    text = p.read_text()
    assert "A demo module." in text
    assert "X = 1\n" in text


def test_artifact_writer_writes_json(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write_json("config.json", {"a": 1})
    text = p.read_text()
    assert "\"a\": 1" in text


def test_audit_engine_detects_placeholder(tmp_path):
    audit = AuditEngine()
    findings = audit.audit_text("some code\n...\n")
    assert any("ellipsis" in f["text"].lower() for f in findings)


def test_audit_engine_empty_python_fails(tmp_path):
    audit = AuditEngine()
    p = tmp_path / "empty.py"
    p.write_text("")
    findings = audit.audit_files([str(p)])
    assert any("empty" in f["text"].lower() for f in findings)


def test_workflow_runner_run_completes_with_minimal_setup(tmp_path):
    state_dir = tmp_path / "state"
    log_dir = tmp_path / "log"
    runner = WorkflowRunner(
        "demo-runner",
        requirements="Return hello world.",
        repo_root=tmp_path / "projects" / "demo-runner",
        state_dir=state_dir,
        log_dir=log_dir,
    )
    runner.add_disciplines({
        "engineering": ["backend"],
    })
    report = runner.run()
    assert report["status"] == "COMPLETED"
    assert (tmp_path / "projects" / "demo-runner").exists()


def test_artifact_writer_executable_flag(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("script.sh", "#!/bin/bash\necho hi", executable=True)
    assert (p.stat().st_mode & 0o111) != 0
