"""Tests for crucible.runner (artifact writer + audit engine + workflow runner)."""

from crucible.runner import (
    ARTIFACT_HEADER,
    ArtifactWriter,
    AuditEngine,
    DefaultSubagentWorker,
    WorkflowRunner,
)


def test_artifact_writer_creates_nested_dirs(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("a/b/c/hello.py", "print('hi')\n")
    assert p.exists()
    assert "print('hi')" in p.read_text()
    assert len(writer.list_written()) == 1


def test_artifact_writer_adds_header(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("hello.md", "# Hi\n")
    text = p.read_text()
    assert text.startswith("# Generated by crucible")
    assert "# Hi" in text


def test_artifact_writer_writes_module(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write_module(
        "mymodule.py",
        "A demo module.",
        "X = 1\n",
    )
    text = p.read_text()
    assert "A demo module." in text
    assert "X = 1\n" in text


def test_artifact_writer_writes_json(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write_json("config.json", {"a": 1})
    text = p.read_text()
    assert '"a": 1' in text


def test_audit_engine_detects_placeholder(tmp_path):
    audit = AuditEngine()
    findings = audit.audit_text("some code\n...\n")
    assert any("ellipsis" in f["text"].lower() for f in findings)


def test_audit_engine_empty_python_fails(tmp_path):
    audit = AuditEngine()
    p = tmp_path / "empty.py"
    p.write_text("")
    findings = audit.audit_files([str(p)])
    assert any("empty" in f["text"].lower() for f in findings)


def test_workflow_runner_run_completes_with_minimal_setup(tmp_path):
    state_dir = tmp_path / "state"
    log_dir = tmp_path / "log"
    repo_root = tmp_path / "projects" / "demo-runner"
    runner = WorkflowRunner(
        "demo-runner",
        requirements="Return hello world.",
        repo_root=repo_root,
        state_dir=state_dir,
        log_dir=log_dir,
    )
    runner.add_disciplines({
        "engineering": ["backend"],
    })
    report = runner.run()
    assert report["status"] == "COMPLETED"
    assert repo_root.exists()
    assert any(
        p.name == "app.py"
        for p in (repo_root / "src" / "engineering" / "backend" / "python").rglob("*")
        if p.is_file()
    )


def test_artifact_writer_executable_flag(tmp_path):
    writer = ArtifactWriter(tmp_path / "repo")
    p = writer.write("script.sh", "#!/bin/bash\necho hi", executable=True)
    assert (p.stat().st_mode & 0o111) != 0


def test_default_subagent_worker_returns_python_artifact_bundle(tmp_path):
    worker = DefaultSubagentWorker()
    result = worker.run_language_task(
        "generate python app",
        "python",
        {"repo_root": tmp_path / "repo", "discipline": "engineering", "layer": "backend"},
    )

    assert result.output
    assert list(result.artifacts) == ["README.md", "app.py"]
    assert len(result.artifacts) == 2
    assert "bridge" in result.metadata
    assert result.metadata["real"] is True
    assert result.metadata["written"] == ["README.md", "app.py"]
    assert result.metadata["language"] == "python"
    assert result.metadata["discipline"] == "engineering"
    assert result.metadata["layer"] == "backend"
    assert all((content or "").strip() for content in result.artifacts.values())
    assert result.artifacts["app.py"].strip().startswith("def main() -> None:")
    assert result.artifacts["README.md"].strip().startswith("# Generated by crucible")


def test_default_subagent_worker_returns_typescript_artifact_bundle(tmp_path):
    worker = DefaultSubagentWorker()
    result = worker.run_language_task(
        "generate typescript app",
        "typescript",
        {"repo_root": tmp_path / "repo", "discipline": "design", "layer": "frontend"},
    )

    assert result.output
    assert list(result.artifacts) == ["README.md", "app.ts"]
    assert len(result.artifacts) == 2
    assert "bridge" in result.metadata
    assert result.metadata["real"] is True
    assert result.metadata["written"] == ["README.md", "app.ts"]
    assert result.metadata["language"] == "typescript"
    assert result.metadata["discipline"] == "design"
    assert result.metadata["layer"] == "frontend"
    assert all((content or "").strip() for content in result.artifacts.values())
    assert "console.log(" in result.artifacts["app.ts"]
    assert result.artifacts["README.md"].strip().startswith("# Generated by crucible")


def test_default_subagent_worker_rejects_unsupported_language(tmp_path):
    worker = DefaultSubagentWorker()
    with __import__("pytest").raises(ValueError, match="Unsupported language for DefaultSubagentWorker: 'rust'"):
        worker.run_language_task("task", "rust", {"repo_root": tmp_path / "repo"})


def test_default_subagent_worker_rejects_out_of_tree_paths(tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    assert not DefaultSubagentWorker._is_out_of_tree_rel(
        repo_root, "src/engineering/backend/python/app.py"
    )
    assert DefaultSubagentWorker._is_out_of_tree_rel(
        repo_root, "src/../../evil/app.py"
    )


def test_default_subagent_worker_defaults_discipline_and_layer(tmp_path):
    worker = DefaultSubagentWorker()
    result = worker.run_language_task(
        "task",
        "python",
        {"repo_root": tmp_path / "repo"},
    )

    assert result.metadata["discipline"] == "engineering"
    assert result.metadata["layer"] == "backend"


def test_default_subagent_worker_writes_files_to_repo_root(tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    worker = DefaultSubagentWorker()
    result = worker.run_language_task(
        "generate python app",
        "python",
        {"repo_root": repo_root, "discipline": "engineering", "layer": "backend"},
    )

    app = repo_root / "src/engineering/backend/python/app.py"
    readme = repo_root / "src/engineering/backend/python/README.md"

    assert result.metadata["real"] is True
    assert result.metadata["written"] == ["README.md", "app.py"]
    assert app.exists()
    assert readme.exists()
    assert "def main() -> None:" in app.read_text()
    assert "## Python stub" in readme.read_text()
    assert readme.read_text().startswith(ARTIFACT_HEADER)


def test_default_subagent_worker_type_script_writes_files_to_repo_root(tmp_path):
    repo_root = tmp_path / "repo"
    repo_root.mkdir()

    worker = DefaultSubagentWorker()
    result = worker.run_language_task(
        "generate typescript app",
        "typescript",
        {"repo_root": repo_root, "discipline": "design", "layer": "frontend"},
    )

    app = repo_root / "src/design/frontend/typescript/app.ts"
    readme = repo_root / "src/design/frontend/typescript/README.md"

    assert result.metadata["real"] is True
    assert result.metadata["written"] == ["README.md", "app.ts"]
    assert app.exists()
    assert readme.exists()
    assert "export function main():" in app.read_text()
    assert "## TypeScript stub" in readme.read_text()
    assert readme.read_text().startswith(ARTIFACT_HEADER)
