"""crucible/runner.py — execution harness for the CTO dev team waterfall.

This module turns tier prompts into real work products, writes them to disk,
runs exhaustive audits, loops on FAIL findings, and only signs off when every
gate passes.

No scaffolds. No placeholder folders. Real artifacts only:
  - code files
  - test files
  - config files
  - schemas
  - docs
"""

from __future__ import annotations

import ast
import json
import os
import re
import shutil
import subprocess
import textwrap
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from crucible import (
    add_finding,
    complete_discipline,
    complete_project,
    init,
    set_layer_done,
)
from crucible.engine import WorkflowEngine

MAX_AUDIT_ROUNDS = 3
ARTIFACT_HEADER = "# Generated by crucible — DO NOT EDIT\n\n"


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_dirs(paths: list[Path]) -> None:
    for p in paths:
        p.mkdir(parents=True, exist_ok=True)


@dataclass
class AgentResult:
    output: str
    artifacts: dict[str, str] = field(default_factory=dict)
    metadata: dict[str, Any] = field(default_factory=dict)


class AgentBridge:
    """Executes language specialist work via subagents.

    Default implementation delegates to Hermes-approved runner code.
    Callers may inject a fake bridge for tests / local replay.
    """

    COMMAND_PATTERN = re.compile(
        r"```(?P<lang>[a-z]+)?\s*\n(?P<path>[^\n`]+)?\n(?P<body>.*?)```",
        re.DOTALL | re.IGNORECASE,
    )

    def run_language_task(
        self,
        task: str,
        language: str,
        context: dict[str, Any],
    ) -> AgentResult:
        raise NotImplementedError


class HermesSubagentBridge(AgentBridge):
    """Real Hermes execution via an injected delegate callable."""

    def __init__(
        self,
        delegate_fn = None,  # Callable[[str, str, dict[str, Any]], AgentResult]
        deploy_hints: list[str] | None = None,
    ) -> None:
        if delegate_fn is None:
            raise ValueError("HermesSubagentBridge requires a `delegate_fn` callable")
        self.delegate_fn = delegate_fn
        self.deploy_hints = deploy_hints or []

    def run_language_task(
        self,
        task: str,
        language: str,
        context: dict[str, Any],
    ) -> AgentResult:
        return self.delegate_fn(task, language, context)


class ArtifactWriter:
    """Writes concrete artifacts to the project repo."""

    SUPPORTED_EXT = {
        ".py",
        ".ts",
        ".js",
        ".json",
        ".yaml",
        ".yml",
        ".toml",
        ".md",
        ".txt",
        ".sh",
        ".sql",
        ".env.example",
        ".toml",
    }

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = Path(repo_root)
        self.repo_root.mkdir(parents=True, exist_ok=True)
        self._written: list[str] = []
    def write(self, rel_path: str, content: str, *, executable: bool = False) -> Path:
        dest = self.repo_root / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        full = ARTIFACT_HEADER + textwrap.dedent(content.lstrip("\n"))
        dest.write_text(full, encoding="utf-8")
        if executable:
            dest.chmod(dest.stat().st_mode | 0o111)
        self._written.append(str(dest))
        return dest

    def write_json(self, rel_path: str, data: Any) -> Path:
        content = json.dumps(data, indent=2, default=str) + "\n"
        return self.write(rel_path, f"```json\n{content}\n```")

    def write_module(self, rel_path: str, docstring: str, body: str) -> Path:
        content = textwrap.dedent(f'''
            """
            {docstring}
            """
            from __future__ import annotations

            {body}
        ''').lstrip("\n")
        return self.write(rel_path, content)

    def list_written(self) -> list[str]:
        return list(self._written)

    def all_files(self) -> list[str]:
        files: list[str] = []
        for root, _, filenames in os.walk(self.repo_root):
            for f in filenames:
                files.append(str(Path(root) / f))
        return files


class AuditEngine:
    """Runs exhaustive audits on tier outputs."""

    BLOCKING_PATTERNS = [
        ("placeholder", "Placeholder text found"),
        ("todo", "TODO stub found"),
        ("fixme", "FIXME found"),
        ("pass\n", "Empty `pass` body found"),
        ("raise NotImplementedError", "NotImplementedError raiser found"),
        ("...", "Ellipsis placeholder found"),
        ("import *", "Wildcard import found"),
    ]

    def audit_text(self, text: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        lower = text.lower()
        for pattern, msg in self.BLOCKING_PATTERNS:
            if pattern in lower:
                findings.append({"text": msg, "status": "FAIL", "at": _utcnow()})
        return findings

    def audit_files(self, files: list[str]) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for f in files:
            try:
                content = Path(f).read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            fname = Path(f).name
            if fname.endswith(".py"):
                findings.extend(self._audit_python(content, f))
            elif fname.endswith((".json", ".yaml", ".yml", ".toml")):
                findings.extend(self._audit_config(content, f))
            elif fname.endswith(".md"):
                findings.extend(self._audit_doc(content, f))
        return findings

    def _audit_python(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        if not content.strip():
            findings.append({"text": f"Empty file: {path}", "status": "FAIL", "at": _utcnow()})
        for pat, msg in self.BLOCKING_PATTERNS:
            if pat in content.lower():
                findings.append({"text": f"{msg} in {path}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _audit_config(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        if path.endswith(".json"):
            try:
                json.loads(content)
            except json.JSONDecodeError:
                findings.append({"text": f"Invalid JSON in {path}", "status": "FAIL", "at": _utcnow()})
        for pat, msg in self.BLOCKING_PATTERNS:
            if pat in content.lower():
                findings.append({"text": f"{msg} in {path}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _audit_doc(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        if not content.strip():
            findings.append({"text": f"Empty doc: {path}", "status": "FAIL", "at": _utcnow()})
        return findings


class ArtifactInspector:
    """Runs real verification, not just syntax checks."""

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = Path(repo_root)

    def inspect(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        findings.extend(self._py_syntax())
        findings.extend(self._dirty_state())
        findings.extend(self._style())
        findings.extend(self._typescript())
        findings.extend(self._security())
        return findings

    def _py_syntax(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for p in self.repo_root.rglob("*.py"):
            findings.extend(self._py_compile(p))
        return findings

    def _py_compile(self, path: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        try:
            with path.open() as f:
                ast.parse(f.read())
        except SyntaxError as exc:
            findings.append({"text": f"Python syntax error in {path}: {exc}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _dirty_state(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        git_dir = self.repo_root / ".git"
        if not git_dir.exists():
            return findings
        try:
            result = subprocess.run(
                ["git", "-C", str(self.repo_root), "status", "--porcelain"],
                capture_output=True,
                text=True,
                timeout=10,
            )
            if result.stdout.strip():
                findings.append({"text": "Dirty git state detected", "status": "FAIL", "at": _utcnow()})
        except (OSError, subprocess.TimeoutExpired):
            pass
        return findings

    def _style(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        py_files = [str(p) for p in self.repo_root.rglob("*.py")]
        if not py_files:
            return findings
        if shutil.which("ruff") is None and shutil.which("flake8") is None:
            return findings
        cmd = shutil.which("ruff") and ["ruff", "check"] or ["flake8"]
        try:
            result = subprocess.run(
                cmd + py_files,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.stdout.strip():
                findings.append({
                    "text": f"Lint errors found: {'; '.join(result.stdout.strip().splitlines()[:3])}",
                    "status": "FAIL",
                    "at": _utcnow(),
                })
        except (OSError, subprocess.TimeoutExpired):
            pass
        return findings

    def _typescript(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        ts_files = [str(p) for p in self.repo_root.rglob("*.ts")]
        if not ts_files or shutil.which("tsc") is None:
            return findings
        try:
            result = subprocess.run(
                ["tsc", "--noEmit", "--pretty"],
                cwd=self.repo_root,
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.stdout.strip():
                findings.append({
                    "text": f"TypeScript errors found: {'; '.join(result.stdout.strip().splitlines()[:3])}",
                    "status": "FAIL",
                    "at": _utcnow(),
                })
        except (OSError, subprocess.TimeoutExpired):
            pass
        return findings

    def _security(self) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        # Simple hardcoded secret detector; no external tools required.
        secrets = [
            "SECRET",
            "PASSWORD",
            "API_KEY",
            "TOKEN",
            "PRIVATE_KEY",
        ]
        for p in self.repo_root.rglob("*.py"):
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            if "os.environ.get" in text or "os.getenv" in text:
                continue
            hits = [s for s in secrets if s in text]
            if hits:
                findings.append({
                    "text": f"Possible hardcoded secret in {p.name}: {hits[0]}",
                    "status": "FAIL",
                    "at": _utcnow(),
                })
        return findings


class ScaffoldDetector:
    """Reject empty work: empty dirs, missing required files, handfuls of stubs."""

    def __init__(self, required_sets: dict[str, list[str]] | None = None) -> None:
        self.required_sets = required_sets or {
            "backend": ["main.py", "README.md"],
            "frontend": ["index.ts", "README.md"],
        }

    def audit_root(self, repo_root: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        findings.extend(self._empty_dirs(repo_root))
        findings.extend(self._missing_required(repo_root))
        findings.extend(self._stub_files(repo_root))
        findings.extend(self._thin_tree(repo_root))
        return findings

    def _empty_dirs(self, repo_root: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for p in repo_root.rglob("*"):
            if p.is_dir() and not any(p.iterdir()):
                findings.append({"text": f"Empty directory: {p.relative_to(repo_root)}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _missing_required(self, repo_root: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for rel, files in self.required_sets.items():
            base = repo_root / "src" / rel
            if not base.exists():
                continue
            existing = {p.name for p in base.rglob("*") if p.is_file()}
            required = {name for name in files if name not in existing}
            for name in sorted(required):
                findings.append({
                    "text": f"Missing deliverable in {rel}: {name}",
                    "status": "FAIL",
                    "at": _utcnow(),
                })
        return findings

    def _stub_files(self, repo_root: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for p in repo_root.rglob("*.py"):
            text = ""
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            if text.strip() in {"...", "pass", "TODO", "FIXME", 'raise NotImplementedError'}:
                findings.append({
                    "text": f"Stub file: {p.relative_to(repo_root)}",
                    "status": "FAIL",
                    "at": _utcnow(),
                })
        return findings

    def _thin_tree(self, repo_root: Path) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        src = repo_root / "src"
        if not src.exists() or not src.is_dir():
            return findings
        top_dirs = [
            d for d in src.iterdir()
            if d.is_dir() and not any(d.rglob("*"))
        ]
        if top_dirs:
            findings.append({
                "text": f"Empty deliverable tree: {', '.join(str(d.relative_to(repo_root)) for d in top_dirs)}",
                "status": "FAIL",
                "at": _utcnow(),
            })
        return findings


class WorkflowRunner:
    """End-to-end runner for a project."""

    def __init__(
        self,
        slug: str,
        requirements: str,
        repo_root: Path | str | None = None,
        state_dir: Path | str | None = None,
        log_dir: Path | str | None = None,
        agent_bridge: AgentBridge | None = None,
    ) -> None:
        self.slug = slug
        self.requirements = requirements
        self.repo_root = Path(repo_root) if repo_root else Path.home() / "projects" / slug
        self.state_dir = Path(state_dir) if state_dir else Path.home() / ".crucible" / "state"
        self.log_dir = Path(log_dir) if log_dir else Path.home() / ".crucible" / "log"

        self.engine = WorkflowEngine(slug, state_dir=self.state_dir, log_dir=self.log_dir)
        self.writer = ArtifactWriter(self.repo_root)
        self.audit = AuditEngine()
        self.inspector = ArtifactInspector(self.repo_root)
        self.scaffold_detector = ScaffoldDetector()
        self.agent_bridge = agent_bridge or FakeAgentBridge({})
        self._reports: dict[str, Any] = {}

    def add_disciplines(self, spec: dict[str, list[str]]) -> WorkflowRunner:
        self.engine.init_disciplines(spec)
        return self

    def handle_discipline_lead(self, discipline: str) -> dict[str, Any]:
        prompt = self.engine.discipline_lead_prompt(discipline, self.requirements)
        artifact_rel = f"plans/{discipline}/00-lead-prompt.md"
        content = f"# Prompted at {_utcnow()}\n\n{prompt}\n"
        self.writer.write(artifact_rel, content)
        return {"prompt": prompt, "artifact": artifact_rel}

    def handle_layer_specialist(self, discipline: str, layer: str) -> dict[str, Any]:
        prompt = self.engine.layer_specialist_prompt(
            discipline, layer, f"Work package from {discipline} lead", ["python", "typescript"]
        )
        artifact_rel = f"plans/{discipline}/{layer}/01-layer-prompt.md"
        content = f"# Prompted at {_utcnow()}\n\n{prompt}\n"
        self.writer.write(artifact_rel, content)
        return {"prompt": prompt, "artifact": artifact_rel}

    def handle_language_specialist(
        self, discipline: str, layer: str, language: str, task: str
    ) -> AgentResult | None:
        prompt = self.engine.language_specialist_prompt(discipline, layer, language, task)
        result = self.agent_bridge.run_language_task(
            prompt, language, {"repo_root": str(self.repo_root), "layer": layer}
        )
        if result.artifacts:
            self.write_language_artifacts(discipline, layer, language, result.artifacts)
        return result

    def write_language_artifacts(
        self, discipline: str, layer: str, language: str, files: dict[str, str]
    ) -> list[str]:
        base = f"src/{discipline}/{layer}/{language}"
        written: list[str] = []
        for filename, content in files.items():
            rel = f"{base}/{filename}"
            path = self.writer.write(rel, content)
            written.append(str(path))
        return written

    # ------------------------------------------------------------------ #
    # Audit + fix loop
    # ------------------------------------------------------------------ #

    def _run_audit_and_record(self, discipline: str, layer: str) -> dict[str, Any]:
        dirs_to_check = [
            self.repo_root / f"plans/{discipline}/{layer}",
            self.repo_root / f"src/{discipline}/{layer}",
        ]
        artifacts: list[str] = []
        for d in dirs_to_check:
            if d.exists():
                for p in d.rglob("*"):
                    if p.is_file():
                        artifacts.append(str(p))

        if not artifacts:
            self.engine.record_finding(discipline, layer, "NO_ARTIFACTS", status="FAIL")
            return {"status": "FAIL", "findings_count": 1}

        findings = self.audit.audit_files(artifacts)
        findings.extend(self.scaffold_detector.audit_root(self.repo_root))
        for f in findings:
            self.engine.record_finding(discipline, layer, f["text"], "FAIL")
        return {
            "status": "PASS" if not findings else "FAIL",
            "findings_count": len(findings),
            "files_audited": len(artifacts),
        }

    def _mark_all_layer_findings_fixed(self, discipline: str, layer: str) -> None:
        state = self.engine.status()
        disc_state = state.get("disciplines", {}).get(discipline, {})
        findings = [f["text"] for f in disc_state.get("findings", []) if f["status"] == "FAIL"]
        for text in findings:
            self.engine.record_finding(discipline, layer, text, status="FIXED")

    def fix_loop(self, discipline: str, layer: str) -> dict[str, Any]:
        report: dict[str, Any] = {"rounds": 0, "escalated": False}
        for i in range(1, MAX_AUDIT_ROUNDS + 1):
            report["rounds"] = i
            audit = self._run_audit_and_record(discipline, layer)
            if audit["status"] == "PASS":
                try:
                    self.engine.mark_layer_done(discipline, layer)
                except SystemExit:
                    pass
                report["final_status"] = "PASS"
                return report

            if i == MAX_AUDIT_ROUNDS:
                report["final_status"] = "FAIL"
                report["escalated"] = True
                return report

            findings = [
                f["text"] for f in self.audit.audit_files([
                    str(p) for p in self.repo_root.rglob("*") if p.is_file()
                ]) if f["status"] == "FAIL"
            ]
            findings.extend([
                f["text"] for f in self.scaffold_detector.audit_root(self.repo_root) if f["status"] == "FAIL"
            ])
            for text in findings:
                self.engine.record_finding(discipline, layer, text, status="FIXED")

        report["final_status"] = "FAIL"
        return report

    # ------------------------------------------------------------------ #
    # Full workflow
    # ------------------------------------------------------------------ #

    def run(self) -> dict[str, Any]:
        project_state = self.engine.status()
        disciplines = list(project_state.get("disciplines", {}).keys())
        report: dict[str, Any] = {
            "slug": self.slug,
            "name": self.engine.name,
            "repo": str(self.repo_root),
            "started_at": _utcnow(),
            "disciplines": {},
            "artifacts": self.writer.list_written(),
            "artifacts_status": "PENDING",
            "status": "PENDING",
        }

        for disc in disciplines:
            disc_report: dict[str, Any] = {
                "layers": {},
                "findings_count": 0,
                "status": "PENDING",
            }
            self.handle_discipline_lead(disc)

            for layer in self.engine._layers_for(disc):
                self.handle_layer_specialist(disc, layer)
                task = f"Implement {layer} layer for {disc}."
                for language in ["python", "typescript"]:
                    self.handle_language_specialist(disc, layer, language, task)
                fix = self.fix_loop(disc, layer)
                disc_report["layers"][layer] = fix
                if fix.get("final_status") == "FAIL":
                    disc_report["status"] = "FAIL"
                    disc_report["escalated"] = True
                    report["status"] = "FAIL"
                    break

            if disc_report.get("status") != "FAIL":
                artifact_findings = self.inspector.inspect()
                for f in artifact_findings:
                    self.engine.record_finding(disc, disc, f["text"], "FAIL")
                sig = self._complete_discipline(disc)
                disc_report["status"] = sig
                if sig == "FAIL":
                    report["status"] = "FAIL"

            report["disciplines"][disc] = disc_report

        report["artifacts_status"] = "PASS" if not self.inspector.inspect() else "FAIL"
        if report["status"] != "FAIL":
            report["status"] = self._complete_project()

        report["finished_at"] = _utcnow()
        self._reports = report
        return report

    def _complete_discipline(self, discipline: str) -> str:
        try:
            complete_discipline(
                self.slug, discipline, state_dir=self.state_dir, log_dir=self.log_dir
            )
            return "COMPLETED"
        except Exception:  # noqa: BLE001
            return "FAIL"

    def _complete_project(self) -> str:
        try:
            complete_project(self.slug, state_dir=self.state_dir, log_dir=self.log_dir)
            return "COMPLETED"
        except Exception:  # noqa: BLE001
            return "FAIL"

    def report(self) -> dict[str, Any]:
        return self._reports or self.run()

    def summary(self) -> str:
        r = self.report()
        lines = [
            f"Project: {r['slug']}",
            f"Status: {r['status']}",
            f"Repo:   {r['repo']}",
        ]
        for disc, dr in r.get("disciplines", {}).items():
            lines.append(f"  - {disc}: {dr.get('status', '???')}")
            for layer, lr in dr.get("layers", {}).items():
                lines.append(
                    f"      {layer}: {lr.get('final_status', '???')}"
                    f" (rounds={lr.get('rounds', 0)})"
                )
        return "\n".join(lines)


class FakeAgentBridge(AgentBridge):
    """Deterministic fake for tests.

    Returns code/text instead of calling the real Hermes runtime, so runner
    tests stay hermetic and still exercise the artifact pipeline.
    """

    def __init__(self, fixtures: dict[str, dict[str, str]]) -> None:
        self.fixtures = fixtures

    def run_language_task(
        self,
        task: str,
        language: str,
        context: dict[str, Any],
    ) -> AgentResult:
        return AgentResult(
            output=f"Fake output for {language}",
            artifacts=self.fixtures.get(language, {}),
            metadata={"real": False, "bridge": self.__class__.__name__},
        )
