"""crucible/runner.py — execution harness for the CTO dev team waterfall.

This module turns tier prompts into real work products, writes them to disk,
runs exhaustive audits, loops on FAIL findings, and only signs off when every
gate passes.

No scaffolds. No placeholder folders. Real artifacts only:
  - code files
  - test files
  - config files
  - schemas
  - docs
"""

from __future__ import annotations

import json
import os
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from crucible import (
    add_discipline,
    add_finding,
    complete_discipline,
    complete_project,
    init,
    load,
    set_layer_done,
)
from crucible.engine import WorkflowEngine

MAX_AUDIT_ROUNDS = 3
ARTIFACT_HEADER = "# Generated by crucible — DO NOT EDIT\n\n"


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _ensure_dirs(paths: list[Path]) -> None:
    for p in paths:
        p.parent.mkdir(parents=True, exist_ok=True)


class ArtifactWriter:
    """Writes concrete artifacts to the project repo."""

    SUPPORTED_EXT = {
        ".py",
        ".ts",
        ".js",
        ".json",
        ".yaml",
        ".yml",
        ".toml",
        ".md",
        ".txt",
        ".sh",
        ".sql",
        ".env.example",
    }

    def __init__(self, repo_root: Path) -> None:
        self.repo_root = Path(repo_root)
        self.repo_root.mkdir(parents=True, exist_ok=True)
        self._written: list[str] = []

    def write(self, rel_path: str, content: str, *, executable: bool = False) -> Path:
        """Write a single artifact, creating directories as needed."""
        dest = self.repo_root / rel_path
        _ensure_dirs([dest])
        full = ARTIFACT_HEADER + textwrap.dedent(content.lstrip("\n"))
        dest.write_text(full, encoding="utf-8")
        if executable:
            dest.chmod(dest.stat().st_mode | 0o111)
        self._written.append(str(dest))
        return dest

    def write_json(self, rel_path: str, data: Any) -> Path:
        content = json.dumps(data, indent=2, default=str) + "\n"
        return self.write(rel_path, f"```json\n{content}\n```")

    def write_module(self, rel_path: str, docstring: str, body: str) -> Path:
        content = textwrap.dedent(f'''
            """
            {docstring}
            """
            from __future__ import annotations

            {body}
        ''').lstrip("\n")
        return self.write(rel_path, content)

    def list_written(self) -> list[str]:
        return list(self._written)

    def all_files(self) -> list[str]:
        files: list[str] = []
        for root, _, filenames in os.walk(self.repo_root):
            for f in filenames:
                files.append(str(Path(root) / f))
        return files


class AuditEngine:
    """Runs exhaustive audits on tier outputs.

    Each tier is checked against the full audit checklist:
    - Functional completeness
    - Correctness
    - Consistency
    - Completeness
    - Hygiene
    """

    BLOCKING_PATTERNS = [
        ("placeholder", "Placeholder text found"),
        ("todo", "TODO stub found"),
        ("fixme", "FIXME found"),
        ("pass\n", "Empty `pass` body found"),
        ("raise NotImplementedError", "NotImplementedError raiser found"),
        ("...", "Ellipsis placeholder found"),
        ("import *", "Wildcard import found"),
    ]

    def audit_text(self, text: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        lower = text.lower()
        for pattern, msg in self.BLOCKING_PATTERNS:
            if pattern in lower:
                findings.append({"text": msg, "status": "FAIL", "at": _utcnow()})
        return findings

    def audit_files(self, files: list[str]) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        for f in files:
            try:
                content = Path(f).read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            fname = Path(f).name
            if fname.endswith(".py"):
                findings.extend(self._audit_python(content, f))
            elif fname.endswith((".json", ".yaml", ".yml", ".toml")):
                findings.extend(self._audit_config(content, f))
            elif fname.endswith(".md"):
                findings.extend(self._audit_doc(content, f))
        return findings

    def _audit_python(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        stripped = content.strip()
        if not stripped:
            findings.append({"text": f"Empty file: {path}", "status": "FAIL", "at": _utcnow()})
        for pat, msg in self.BLOCKING_PATTERNS:
            if pat in content.lower():
                findings.append({"text": f"{msg} in {path}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _audit_config(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        try:
            json.loads(content)
        except json.JSONDecodeError:
            findings.append({"text": f"Invalid JSON in {path}", "status": "FAIL", "at": _utcnow()})
        for pat, msg in self.BLOCKING_PATTERNS:
            if pat in content.lower():
                findings.append({"text": f"{msg} in {path}", "status": "FAIL", "at": _utcnow()})
        return findings

    def _audit_doc(self, content: str, path: str) -> list[dict[str, str]]:
        findings: list[dict[str, str]] = []
        if not content.strip():
            findings.append({"text": f"Empty doc: {path}", "status": "FAIL", "at": _utcnow()})
        return findings


class WorkflowRunner:
    """End-to-end runner for a project.

    Usage:
        runner = WorkflowRunner("myapp", requirements=req_text)
        runner.add_disciplines({
            "engineering": ["backend", "frontend"],
            "qa": ["unit", "integration"],
        })
        report = runner.run()
    """

    def __init__(
        self,
        slug: str,
        requirements: str,
        repo_root: Path | str | None = None,
        state_dir: Path | str | None = None,
        log_dir: Path | str | None = None,
    ) -> None:
        self.slug = slug
        self.requirements = requirements
        self.repo_root = Path(repo_root) if repo_root else Path.home() / "projects" / slug
        self.state_dir = Path(state_dir) if state_dir else Path.home() / ".crucible" / "state"
        self.log_dir = Path(log_dir) if log_dir else Path.home() / ".crucible" / "log"

        self.engine = WorkflowEngine(slug, state_dir=self.state_dir, log_dir=self.log_dir)
        self.writer = ArtifactWriter(self.repo_root)
        self.audit = AuditEngine()
        self._reports: dict[str, Any] = {}

    # ------------------------------------------------------------------ #
    # Setup
    # ------------------------------------------------------------------ #

    def add_disciplines(self, spec: dict[str, list[str]]) -> WorkflowRunner:
        self.engine.init_disciplines(spec)
        return self

    # ------------------------------------------------------------------ #
    # Tier output handlers
    # ------------------------------------------------------------------ #

    def handle_discipline_lead(self, discipline: str) -> dict[str, Any]:
        """Run discipline lead prompt and write output."""
        prompt = self.engine.discipline_lead_prompt(discipline, self.requirements)
        artifact_rel = f"plans/{discipline}/00-lead-prompt.md"
        content = f"# Prompted at {_utcnow()}\n\n{prompt}\n"
        self.writer.write(artifact_rel, content)
        return {"prompt": prompt, "artifact": artifact_rel}

    def handle_layer_specialist(self, discipline: str, layer: str) -> dict[str, Any]:
        prompt = self.engine.layer_specialist_prompt(
            discipline, layer, f"Work package from {discipline} lead", ["python", "typescript"]
        )
        artifact_rel = f"plans/{discipline}/{layer}/01-layer-prompt.md"
        content = f"# Prompted at {_utcnow()}\n\n{prompt}\n"
        self.writer.write(artifact_rel, content)
        return {"prompt": prompt, "artifact": artifact_rel}

    def handle_language_specialist(
        self, discipline: str, layer: str, language: str
    ) -> dict[str, Any]:
        prompt = self.engine.language_specialist_prompt(
            discipline, layer, language, f"Implementation task for {layer} in {language}"
        )
        artifact_rel = f"plans/{discipline}/{layer}/{language}/02-language-prompt.md"
        content = f"# Prompted at {_utcnow()}\n\n{prompt}\n"
        self.writer.write(artifact_rel, content)
        return {"prompt": prompt, "artifact": artifact_rel}

    def write_language_artifacts(
        self,
        discipline: str,
        layer: str,
        language: str,
        files: dict[str, str],
    ) -> list[str]:
        """Write actual language artifacts (code, tests, configs) to disk."""
        base = f"src/{discipline}/{layer}/{language}"
        written: list[str] = []
        for filename, content in files.items():
            rel = f"{base}/{filename}"
            path = self.writer.write(rel, content)
            written.append(str(path))
        return written

    # ------------------------------------------------------------------ #
    # Audit + fix loop
    # ------------------------------------------------------------------ #

    def _run_audit_and_record(self, discipline: str, layer: str) -> dict[str, Any]:
        """Run audit on the current layer tree and record findings."""
        dirs_to_check = [
            self.repo_root / f"plans/{discipline}/{layer}",
            self.repo_root / f"src/{discipline}/{layer}",
        ]
        artifacts: list[str] = []
        for d in dirs_to_check:
            if d.exists():
                for p in d.rglob("*"):
                    if p.is_file():
                        artifacts.append(str(p))

        if not artifacts:
            self.engine.record_finding(discipline, layer, "NO_ARTIFACTS", status="FAIL")
            return {"status": "FAIL", "findings_count": 1}

        findings = self.audit.audit_files(artifacts)
        for f in findings:
            self.engine.record_finding(discipline, layer, f["text"], "FAIL")
        return {
            "status": "PASS" if not findings else "FAIL",
            "findings_count": len(findings),
            "files_audited": len(artifacts),
        }

    def _mark_all_layer_findings_fixed(self, discipline: str, layer: str) -> None:
        state = self.engine.status()
        disc_state = state.get("disciplines", {}).get(discipline, {})
        findings = [f["text"] for f in disc_state.get("findings", []) if f["status"] == "FAIL"]
        for text in findings:
            self.engine.record_finding(discipline, layer, text, status="FIXED")

    def fix_loop(self, discipline: str, layer: str) -> dict[str, Any]:
        """Loop until the layer passes audit or MAX_AUDIT_ROUNDS is exhausted."""
        report: dict[str, Any] = {"rounds": 0, "escalated": False}
        for i in range(1, MAX_AUDIT_ROUNDS + 1):
            report["rounds"] = i
            audit = self._run_audit_and_record(discipline, layer)
            if audit["status"] == "PASS":
                try:
                    self.engine.mark_layer_done(discipline, layer)
                except SystemExit:
                    pass
                report["final_status"] = "PASS"
                return report

            if i == MAX_AUDIT_ROUNDS:
                report["final_status"] = "FAIL"
                report["escalated"] = True
                return report

            self._mark_all_layer_findings_fixed(discipline, layer)

        report["final_status"] = "FAIL"
        return report

    # ------------------------------------------------------------------ #
    # Full workflow
    # ------------------------------------------------------------------ #

    def run(self) -> dict[str, Any]:
        """Drive the full waterfall end-to-end."""
        project_state = self.engine.status()
        disciplines = list(project_state.get("disciplines", {}).keys())
        report: dict[str, Any] = {
            "slug": self.slug,
            "name": self.engine.name,
            "repo": str(self.repo_root),
            "started_at": _utcnow(),
            "disciplines": {},
            "artifacts": self.writer.list_written(),
            "status": "PENDING",
        }

        for disc in disciplines:
            disc_report: dict[str, Any] = {
                "layers": {},
                "findings_count": 0,
                "status": "PENDING",
            }
            self.handle_discipline_lead(disc)

            for layer in self.engine._layers_for(disc):
                self.handle_layer_specialist(disc, layer)
                for language in ["python", "typescript"]:
                    self.handle_language_specialist(disc, layer, language)
                fix = self.fix_loop(disc, layer)
                disc_report["layers"][layer] = fix
                if fix.get("final_status") == "FAIL":
                    disc_report["status"] = "FAIL"
                    disc_report["escalated"] = True
                    report["status"] = "FAIL"
                    break

            if disc_report.get("status") != "FAIL":
                sig = self._complete_discipline(disc)
                disc_report["status"] = sig
                if sig == "FAIL":
                    report["status"] = "FAIL"

            report["disciplines"][disc] = disc_report

        if report["status"] != "FAIL":
            report["status"] = self._complete_project()

        report["finished_at"] = _utcnow()
        self._reports = report
        return report

    def _complete_discipline(self, discipline: str) -> str:
        try:
            complete_discipline(
                self.slug, discipline, state_dir=self.state_dir, log_dir=self.log_dir
            )
            return "COMPLETED"
        except (SystemExit, Exception):  # noqa: BLE001 - swallow crucible state failures gracefully
            return "FAIL"

    def _complete_project(self) -> str:
        try:
            complete_project(self.slug, state_dir=self.state_dir, log_dir=self.log_dir)
            return "COMPLETED"
        except (SystemExit, Exception):  # noqa: BLE001
            return "FAIL"

    def report(self) -> dict[str, Any]:
        return self._reports or self.run()

    def summary(self) -> str:
        r = self.report()
        lines = [
            f"Project: {r['slug']}",
            f"Status: {r['status']}",
            f"Repo:   {r['repo']}",
            "Disciplines:",
        ]
        for disc, dr in r.get("disciplines", {}).items():
            lines.append(f"  - {disc}: {dr.get('status', '???')}")
            for layer, lr in dr.get("layers", {}).items():
                lines.append(
                    f"      {layer}: {lr.get('final_status', '???')}"
                    f" (rounds={lr.get('rounds', 0)})"
                )
        return "\n".join(lines)
